//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.DomainModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<NLog> NLog { get; set; }
        public virtual DbSet<tbBankCardNumbers> tbBankCardNumbers { get; set; }
        public virtual DbSet<tbBotSettings> tbBotSettings { get; set; }
        public virtual DbSet<tbConnectionHelp> tbConnectionHelp { get; set; }
        public virtual DbSet<tbDepositWallet_Log> tbDepositWallet_Log { get; set; }
        public virtual DbSet<tbExpLog> tbExpLog { get; set; }
        public virtual DbSet<tbFailureServers> tbFailureServers { get; set; }
        public virtual DbSet<tbLinks> tbLinks { get; set; }
        public virtual DbSet<tbLinkUserAndPlans> tbLinkUserAndPlans { get; set; }
        public virtual DbSet<tbLogs> tbLogs { get; set; }
        public virtual DbSet<tbOrders> tbOrders { get; set; }
        public virtual DbSet<tbPlans> tbPlans { get; set; }
        public virtual DbSet<tbServers> tbServers { get; set; }
        public virtual DbSet<tbTelegramUsers> tbTelegramUsers { get; set; }
        public virtual DbSet<tbUpdateLogs> tbUpdateLogs { get; set; }
        public virtual DbSet<tbUseages> tbUseages { get; set; }
        public virtual DbSet<tbUserFactors> tbUserFactors { get; set; }
        public virtual DbSet<tbUsers> tbUsers { get; set; }
    }
}
