//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.DomainModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<NLog> NLog { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<tbBankCardNumbers> tbBankCardNumbers { get; set; }
        public virtual DbSet<tbBotSettings> tbBotSettings { get; set; }
        public virtual DbSet<tbConnectionHelp> tbConnectionHelp { get; set; }
        public virtual DbSet<tbDepositWallet_Log> tbDepositWallet_Log { get; set; }
        public virtual DbSet<tbExpLog> tbExpLog { get; set; }
        public virtual DbSet<tbFailureServers> tbFailureServers { get; set; }
        public virtual DbSet<tbFirebaseMobileTokens> tbFirebaseMobileTokens { get; set; }
        public virtual DbSet<tbLinks> tbLinks { get; set; }
        public virtual DbSet<tbLinkServerGroupWithUsers> tbLinkServerGroupWithUsers { get; set; }
        public virtual DbSet<tbLinkUserAndPlans> tbLinkUserAndPlans { get; set; }
        public virtual DbSet<tbLogs> tbLogs { get; set; }
        public virtual DbSet<tbNotifications> tbNotifications { get; set; }
        public virtual DbSet<tbNotificationUser> tbNotificationUser { get; set; }
        public virtual DbSet<tbOrders> tbOrders { get; set; }
        public virtual DbSet<tbPlans> tbPlans { get; set; }
        public virtual DbSet<tbRedisInfo> tbRedisInfo { get; set; }
        public virtual DbSet<tbServerGroups> tbServerGroups { get; set; }
        public virtual DbSet<tbServers> tbServers { get; set; }
        public virtual DbSet<tbSocks5> tbSocks5 { get; set; }
        public virtual DbSet<tbTelegramUsers> tbTelegramUsers { get; set; }
        public virtual DbSet<tbUpdateLogs> tbUpdateLogs { get; set; }
        public virtual DbSet<tbUseages> tbUseages { get; set; }
        public virtual DbSet<tbUserFactors> tbUserFactors { get; set; }
        public virtual DbSet<tbUsers> tbUsers { get; set; }
        public virtual DbSet<tbHistoryChats> tbHistoryChats { get; set; }
    
        public virtual ObjectResult<GetBotSales_Result> GetBotSales()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetBotSales_Result>("GetBotSales");
        }
    
        public virtual ObjectResult<GetFullSales_Result> GetFullSales()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetFullSales_Result>("GetFullSales");
        }
    
        public virtual ObjectResult<GetMasterUserSales_Result> GetMasterUserSales()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetMasterUserSales_Result>("GetMasterUserSales");
        }
    
        public virtual ObjectResult<GetUserSales_Result> GetUserSales()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetUserSales_Result>("GetUserSales");
        }
    
        public virtual int NLog_AddEntry_p(string machineName, Nullable<System.DateTime> logged, string level, string message, string logger, string properties, string exception, string ipAddress, string requestData, string responseData, string userId, string userName, string userRole, string requestUrl, string httpMethod, string requestHeaders, string userAgent, string executionTime, string sessionId, string actionName, string controllerName, string customData)
        {
            var machineNameParameter = machineName != null ?
                new ObjectParameter("machineName", machineName) :
                new ObjectParameter("machineName", typeof(string));
    
            var loggedParameter = logged.HasValue ?
                new ObjectParameter("logged", logged) :
                new ObjectParameter("logged", typeof(System.DateTime));
    
            var levelParameter = level != null ?
                new ObjectParameter("level", level) :
                new ObjectParameter("level", typeof(string));
    
            var messageParameter = message != null ?
                new ObjectParameter("message", message) :
                new ObjectParameter("message", typeof(string));
    
            var loggerParameter = logger != null ?
                new ObjectParameter("logger", logger) :
                new ObjectParameter("logger", typeof(string));
    
            var propertiesParameter = properties != null ?
                new ObjectParameter("properties", properties) :
                new ObjectParameter("properties", typeof(string));
    
            var exceptionParameter = exception != null ?
                new ObjectParameter("exception", exception) :
                new ObjectParameter("exception", typeof(string));
    
            var ipAddressParameter = ipAddress != null ?
                new ObjectParameter("ipAddress", ipAddress) :
                new ObjectParameter("ipAddress", typeof(string));
    
            var requestDataParameter = requestData != null ?
                new ObjectParameter("requestData", requestData) :
                new ObjectParameter("requestData", typeof(string));
    
            var responseDataParameter = responseData != null ?
                new ObjectParameter("responseData", responseData) :
                new ObjectParameter("responseData", typeof(string));
    
            var userIdParameter = userId != null ?
                new ObjectParameter("userId", userId) :
                new ObjectParameter("userId", typeof(string));
    
            var userNameParameter = userName != null ?
                new ObjectParameter("userName", userName) :
                new ObjectParameter("userName", typeof(string));
    
            var userRoleParameter = userRole != null ?
                new ObjectParameter("userRole", userRole) :
                new ObjectParameter("userRole", typeof(string));
    
            var requestUrlParameter = requestUrl != null ?
                new ObjectParameter("requestUrl", requestUrl) :
                new ObjectParameter("requestUrl", typeof(string));
    
            var httpMethodParameter = httpMethod != null ?
                new ObjectParameter("httpMethod", httpMethod) :
                new ObjectParameter("httpMethod", typeof(string));
    
            var requestHeadersParameter = requestHeaders != null ?
                new ObjectParameter("requestHeaders", requestHeaders) :
                new ObjectParameter("requestHeaders", typeof(string));
    
            var userAgentParameter = userAgent != null ?
                new ObjectParameter("userAgent", userAgent) :
                new ObjectParameter("userAgent", typeof(string));
    
            var executionTimeParameter = executionTime != null ?
                new ObjectParameter("executionTime", executionTime) :
                new ObjectParameter("executionTime", typeof(string));
    
            var sessionIdParameter = sessionId != null ?
                new ObjectParameter("sessionId", sessionId) :
                new ObjectParameter("sessionId", typeof(string));
    
            var actionNameParameter = actionName != null ?
                new ObjectParameter("actionName", actionName) :
                new ObjectParameter("actionName", typeof(string));
    
            var controllerNameParameter = controllerName != null ?
                new ObjectParameter("controllerName", controllerName) :
                new ObjectParameter("controllerName", typeof(string));
    
            var customDataParameter = customData != null ?
                new ObjectParameter("customData", customData) :
                new ObjectParameter("customData", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NLog_AddEntry_p", machineNameParameter, loggedParameter, levelParameter, messageParameter, loggerParameter, propertiesParameter, exceptionParameter, ipAddressParameter, requestDataParameter, responseDataParameter, userIdParameter, userNameParameter, userRoleParameter, requestUrlParameter, httpMethodParameter, requestHeadersParameter, userAgentParameter, executionTimeParameter, sessionIdParameter, actionNameParameter, controllerNameParameter, customDataParameter);
        }
    
        public virtual int SqlQueryNotificationStoredProcedure_2d2da058_e278_4966_9e25_793e672ed0fe()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SqlQueryNotificationStoredProcedure_2d2da058_e278_4966_9e25_793e672ed0fe");
        }
    
        public virtual int SqlQueryNotificationStoredProcedure_4ffd34bb_37a2_4227_8286_fc1e19e68f11()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SqlQueryNotificationStoredProcedure_4ffd34bb_37a2_4227_8286_fc1e19e68f11");
        }
    
        public virtual int SqlQueryNotificationStoredProcedure_90a52481_b600_46ad_a1e7_d3a4b4f41c26()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SqlQueryNotificationStoredProcedure_90a52481_b600_46ad_a1e7_d3a4b4f41c26");
        }
    
        public virtual int SqlQueryNotificationStoredProcedure_a18aa4bb_45b7_493a_9d09_f78f1462150b()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SqlQueryNotificationStoredProcedure_a18aa4bb_45b7_493a_9d09_f78f1462150b");
        }
    
        public virtual int SqlQueryNotificationStoredProcedure_a28a156b_096d_4328_a3f8_bff243f47f1b()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SqlQueryNotificationStoredProcedure_a28a156b_096d_4328_a3f8_bff243f47f1b");
        }
    
        public virtual int SqlQueryNotificationStoredProcedure_e1259852_46ea_4433_b261_181d7c332764()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SqlQueryNotificationStoredProcedure_e1259852_46ea_4433_b261_181d7c332764");
        }
    }
}
