//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class NLog
    {
        public int ID { get; set; }
        public string MachineName { get; set; }
        public System.DateTime Logged { get; set; }
        public string Level { get; set; }
        public string Message { get; set; }
        public string ipAddress { get; set; }
        public string userName { get; set; }
        public string httpMethod { get; set; }
        public string requestData { get; set; }
        public string actionName { get; set; }
        public string controllerName { get; set; }
        public string Properties { get; set; }
        public string Exception { get; set; }
        public string responseData { get; set; }
        public string userId { get; set; }
        public string userRole { get; set; }
        public string requestUrl { get; set; }
        public string requestHeaders { get; set; }
        public string userAgent { get; set; }
        public string executionTime { get; set; }
        public string sessionId { get; set; }
        public string Logger { get; set; }
        public string customData { get; set; }
    }
}
