//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.DomainModel
{
    using System;
    using System.Collections.Generic;

    public partial class tbAlertSendLogs
    {
        public int tbAsl_ID { get; set; }
        public Nullable<int> FK_User_ID { get; set; }
        public string tbAsl_RecipientName { get; set; }
        public string tbAsl_ChatId { get; set; }
        public string tbAsl_AlertType { get; set; }
        public string tbAsl_Message { get; set; }
        public System.DateTime tbAsl_SentAt { get; set; }
        public bool tbAsl_IsSuccess { get; set; }
        public string tbAsl_Error { get; set; }
    }
}
