//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.DomainModel
{
    using System;
    using System.Collections.Generic;

    public partial class tbAppRelease
    {
        public int tbAr_ID { get; set; }
        public string tbAr_DownloadUrl { get; set; }
        public string tbAr_Version { get; set; }
        public Nullable<int> tbAr_VersionCode { get; set; }
        public string tbAr_Changelog { get; set; }
        public bool tbAr_ForceInstall { get; set; }
        public System.DateTime tbAr_UpdatedAt { get; set; }
    }
}
