//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbBankCardNumbers
    {
        public int CardNumber_ID { get; set; }
        public string CardNumber { get; set; }
        public string BankSmsNumber { get; set; }
        public bool Active { get; set; }
        public string InTheNameOf { get; set; }
        public string phoneNumber { get; set; }
        public int FK_User_ID { get; set; }
    
        public virtual tbUsers tbUsers { get; set; }
    }
}
