//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbBotSettings
    {
        public int botSettingID { get; set; }
        public string Bot_Token { get; set; }
        public string Bot_ID { get; set; }
        public Nullable<int> FK_Plan_ID { get; set; }
        public long AdminBot_ID { get; set; }
        public bool RequiredJoinChannel { get; set; }
        public string ChannelID { get; set; }
        public int FK_User_ID { get; set; }
        public Nullable<double> Present_Discount { get; set; }
        public bool IsActiveSendReceipt { get; set; }
        public bool IsActiveCardToCard { get; set; }
        public bool Enabled { get; set; }
        public string AdminUsername { get; set; }
        public Nullable<double> InvitePercent { get; set; }
        public Nullable<int> GroupId_test { get; set; }
        public Nullable<int> GroupId_testUnlimited { get; set; }
        public string NowPayment_API_KEY { get; set; }
        public string HubSmart_API_KEY { get; set; }
        public bool HubSmartPay_Status { get; set; }
        public bool NowPayment_Status { get; set; }
        public bool IsActiveCard { get; set; }
        public bool Aranex_Status { get; set; }
        public string TronWallet { get; set; }
    
        public virtual tbPlans tbPlans { get; set; }
        public virtual tbUsers tbUsers { get; set; }
    }
}
