//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbBotSettings
    {
        public int botSettingID { get; set; }
        public string Bot_Token { get; set; }
        public string Bot_ID { get; set; }
        public Nullable<long> AdminBot_ID { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<bool> RequiredJoinChannel { get; set; }
        public string ChannelID { get; set; }
        public Nullable<int> PricePerGig_Admin { get; set; }
        public Nullable<int> PricePerMonth_Admin { get; set; }
        public Nullable<int> PricePerGig_Major { get; set; }
        public Nullable<int> PricePerMonth_Major { get; set; }
        public int FK_User_ID { get; set; }
        public Nullable<double> Present_Discount { get; set; }
    
        public virtual tbUsers tbUsers { get; set; }
    }
}
