//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbConnectionHelp
    {
        public int ch_ID { get; set; }
        public string ch_Title { get; set; }
        public string ch_Link { get; set; }
        public Nullable<int> FK_Server_ID { get; set; }
    
        public virtual tbServers tbServers { get; set; }
    }
}
