//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbDepositWallet_Log
    {
        public int dw_ID { get; set; }
        public Nullable<int> FK_TelegramUser_ID { get; set; }
        public Nullable<int> dw_Price { get; set; }
        public string dw_Status { get; set; }
        public Nullable<System.DateTime> dw_CreateDatetime { get; set; }
        public string dw_payment_id { get; set; }
        public Nullable<int> dw_message_id { get; set; }
    
        public virtual tbTelegramUsers tbTelegramUsers { get; set; }
    }
}
