//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbExpLog
    {
        public int exl_ID { get; set; }
        public string exl_Message { get; set; }
        public string exl_Description { get; set; }
        public string exl_MethodName { get; set; }
        public Nullable<int> FK_User_ID { get; set; }
        public Nullable<System.DateTime> exl_CreateDatetime { get; set; }
    
        public virtual tbUsers tbUsers { get; set; }
    }
}
