//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbFirebaseMobileTokens
    {
        public int tbFirebase_ID { get; set; }
        public string tbFirebase_Token { get; set; }
        public string tbFireBase_SubToken { get; set; }
        public int tbFireBase_FK_User_ID { get; set; }
    
        public virtual tbUsers tbUsers { get; set; }
    }
}
