//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbLinks
    {
        public int tbLink_ID { get; set; }
        public Nullable<int> FK_TelegramUserID { get; set; }
        public Nullable<int> FK_Server_ID { get; set; }
        public string tbL_Token { get; set; }
        public string tbL_Email { get; set; }
        public Nullable<bool> tbL_Warning { get; set; }
        public string tb_RandomEmail { get; set; }
    
        public virtual tbServers tbServers { get; set; }
        public virtual tbTelegramUsers tbTelegramUsers { get; set; }
    }
}
