//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbLinkUserAndPlans
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbLinkUserAndPlans()
        {
            this.tbLogs = new HashSet<tbLogs>();
        }
    
        public int Link_PU_ID { get; set; }
        public Nullable<int> L_FK_U_ID { get; set; }
        public Nullable<int> L_FK_P_ID { get; set; }
        public Nullable<bool> L_Status { get; set; }
    
        public virtual tbPlans tbPlans { get; set; }
        public virtual tbUsers tbUsers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbLogs> tbLogs { get; set; }
    }
}
