//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbLinks
    {
        public int tbLink_ID { get; set; }
        public Nullable<int> FK_TelegramUserID { get; set; }
        public Nullable<int> FK_Server_ID { get; set; }
        public string tbL_Token { get; set; }
        public string tbL_Email { get; set; }
        public Nullable<bool> tbL_Warning { get; set; }
        public Nullable<bool> tb_AutoRenew { get; set; }
        public Nullable<int> tb_AutoRenew_V2Plan_ID { get; set; }
        public Nullable<int> tb_ChargeLink_ID { get; set; }
        public Nullable<System.DateTime> tb_ChargeLinkedTime { get; set; }
        public Nullable<int> tb_ChargePlan_ID { get; set; }
        public Nullable<bool> tb_status { get; set; }
        public int ExceededCount { get; set; }
        public Nullable<System.DateTime> ExceededLastTime { get; set; }
    
        public virtual tbServers tbServers { get; set; }
        public virtual tbTelegramUsers tbTelegramUsers { get; set; }
    }
}
