//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbLinkServerGroupWithUsers
    {
        public int GroupUserLink_ID { get; set; }
        public Nullable<int> FK_Group_Id { get; set; }
        public Nullable<int> FK_User_Id { get; set; }
    
        public virtual tbServerGroups tbServerGroups { get; set; }
        public virtual tbUsers tbUsers { get; set; }
    }
}
