//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbLogs
    {
        public int log_ID { get; set; }
        public Nullable<int> FK_Link_User_Plan_ID { get; set; }
        public string Action { get; set; }
        public Nullable<System.DateTime> CreateDatetime { get; set; }
        public string FK_NameUser_ID { get; set; }
        public Nullable<int> SalePrice { get; set; }
        public string PlanName { get; set; }
        public Nullable<int> PlanVolume { get; set; }
        public Nullable<int> PlanMonth { get; set; }
    
        public virtual tbLinkUserAndPlans tbLinkUserAndPlans { get; set; }
    }
}
