//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.DomainModel
{
    using System;
    using System.Collections.Generic;

    public partial class tbMobileUsers
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbMobileUsers()
        {
            this.tbOrders = new HashSet<tbOrders>();
            this.tbDepositWallet_Log = new HashSet<tbDepositWallet_Log>();
            this.tbLinks = new HashSet<tbLinks>();
        }

        public int tbMu_ID { get; set; }
        public Nullable<int> FK_User_ID { get; set; }
        public string tbMu_AndroidId { get; set; }
        public string tbMu_FirebaseToken { get; set; }
        public bool tbMu_NotificationEnabled { get; set; }
        public string tbMu_Manufacturer { get; set; }
        public string tbMu_Model { get; set; }
        public string tbMu_Device { get; set; }
        public string tbMu_Product { get; set; }
        public string tbMu_Hardware { get; set; }
        public string tbMu_AndroidVersion { get; set; }
        public Nullable<int> tbMu_Sdk { get; set; }
        public string tbMu_AppVersion { get; set; }
        public Nullable<int> tbMu_VersionCode { get; set; }
        public string tbMu_PackageName { get; set; }
        public string tbMu_Language { get; set; }
        public string tbMu_Country { get; set; }
        public string tbMu_Timezone { get; set; }
        public Nullable<int> tbMu_ScreenWidth { get; set; }
        public Nullable<int> tbMu_ScreenHeight { get; set; }
        public Nullable<int> tbMu_Density { get; set; }
        public bool tbMu_Rooted { get; set; }
        public Nullable<System.DateTime> tbMu_RegisterDate { get; set; }
        public Nullable<System.DateTime> tbMu_LastSeenDate { get; set; }
        public string tbMu_LastIp { get; set; }
        public bool tbMu_IsActive { get; set; }

        public virtual tbUsers tbUsers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbOrders> tbOrders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbDepositWallet_Log> tbDepositWallet_Log { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbLinks> tbLinks { get; set; }
    }
}
