//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbNotifications
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbNotifications()
        {
            this.tbNotificationUser = new HashSet<tbNotificationUser>();
        }
    
        public int tbNoti_ID { get; set; }
        public int tbNoti_FK_User_ID { get; set; }
        public string tbNoti_Title { get; set; }
        public string tbNoti_Text { get; set; }
        public System.DateTime tbNoti_RegisterDate { get; set; }
        public int tbNoti_Status { get; set; }
        public System.DateTime tbNoti_EndDate { get; set; }
    
        public virtual tbUsers tbUsers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbNotificationUser> tbNotificationUser { get; set; }
    }
}
