//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbNotificationUser
    {
        public int tbNotiUser_ID { get; set; }
        public int tbNoti_FK_Noti_ID { get; set; }
        public int tbNotiUser_FK_User_ID { get; set; }
        public bool tbNotiUser_Seen { get; set; }
        public Nullable<System.DateTime> tbNotiUser_DateSeen { get; set; }
    
        public virtual tbNotifications tbNotifications { get; set; }
        public virtual tbUsers tbUsers { get; set; }
    }
}
