//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbOrders
    {
        public int Order_ID { get; set; }
        public Nullable<int> FK_Plan_ID { get; set; }
        public string AccountName { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public string OrderStatus { get; set; }
        public string OrderType { get; set; }
        public Nullable<int> FK_OrderAdmin_ID { get; set; }
        public Nullable<System.Guid> Order_Guid { get; set; }
        public Nullable<int> V2_User_ID { get; set; }
    
        public virtual tbPlans tbPlans { get; set; }
        public virtual tbUsers tbUsers { get; set; }
    }
}
