//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbOrders
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbOrders()
        {
            this.tbDepositWallet_Log = new HashSet<tbDepositWallet_Log>();
        }
    
        public int Order_ID { get; set; }
        public Nullable<int> V2_Plan_ID { get; set; }
        public Nullable<int> FK_Link_Plan_ID { get; set; }
        public string AccountName { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public string OrderStatus { get; set; }
        public string OrderType { get; set; }
        public Nullable<System.Guid> Order_Guid { get; set; }
        public Nullable<int> Order_Price { get; set; }
        public Nullable<int> PriceWithOutDiscount { get; set; }
        public Nullable<int> FK_Tel_UserID { get; set; }
        public string payment_id { get; set; }
        public Nullable<int> Traffic { get; set; }
        public Nullable<int> Month { get; set; }
        public Nullable<System.DateTime> Tel_RenewedDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbDepositWallet_Log> tbDepositWallet_Log { get; set; }
        public virtual tbLinkUserAndPlans tbLinkUserAndPlans { get; set; }
        public virtual tbTelegramUsers tbTelegramUsers { get; set; }
    }
}
