//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbPanelChangelogVersions
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbPanelChangelogVersions()
        {
            this.tbPanelChangelogItems = new HashSet<tbPanelChangelogItems>();
        }
    
        public int tbPclv_ID { get; set; }
        public string tbPclv_Version { get; set; }
        public string tbPclv_ReleaseDate { get; set; }
        public int tbPclv_SortOrder { get; set; }
        public bool tbPclv_IsCurrent { get; set; }
        public bool tbPclv_IsActive { get; set; }
        public System.DateTime tbPclv_CreatedAt { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbPanelChangelogItems> tbPanelChangelogItems { get; set; }
    }
}
