//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbPaymentMethodUser
    {
        public int tbpu_ID { get; set; }
        public int FK_User_ID { get; set; }
        public int FK_PaymentMethod_ID { get; set; }
        public Nullable<int> FK_Learn_ID { get; set; }
        public string tbpu_ApiKey { get; set; }
        public bool tbpu_Status { get; set; }
    
        public virtual tbConnectionHelp tbConnectionHelp { get; set; }
        public virtual tbPaymentMethods tbPaymentMethods { get; set; }
        public virtual tbUsers tbUsers { get; set; }
    }
}
