//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbPaymentLinks
    {
        public int py_id { get; set; }
        public string py_hash { get; set; }
        public string py_authority { get; set; }
        public int py_amount { get; set; }
        public System.DateTime py_createdate { get; set; }
        public string py_desc { get; set; }
        public bool py_status { get; set; }
        public string py_link_web { get; set; }
        public string py_link_bot { get; set; }
    }
}
