//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.DomainModel
{
    using System;

    public partial class tbPanelChangelogItems
    {
        public int tbPcli_ID { get; set; }
        public int FK_Version_ID { get; set; }
        public string tbPcli_Title { get; set; }
        public string tbPcli_Description { get; set; }
        public byte tbPcli_Audience { get; set; }
        public int tbPcli_SortOrder { get; set; }
        public bool tbPcli_IsActive { get; set; }

        public virtual tbPanelChangelogVersions tbPanelChangelogVersions { get; set; }
    }
}
