//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbPanelChangelogSeen
    {
        public int tbPcls_ID { get; set; }
        public int FK_User_ID { get; set; }
        public string tbPcls_Version { get; set; }
        public System.DateTime tbPcls_SeenAt { get; set; }
    }
}
