//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbPlans
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbPlans()
        {
            this.tbLinks = new HashSet<tbLinks>();
            this.tbLinkUserAndPlans = new HashSet<tbLinkUserAndPlans>();
            this.tbOrders = new HashSet<tbOrders>();
        }
    
        public int Plan_ID { get; set; }
        public Nullable<int> Plan_ID_V2 { get; set; }
        public string Plan_Name { get; set; }
        public Nullable<int> FK_User_ID { get; set; }
        public string Plan_Des { get; set; }
        public Nullable<int> FK_Server_ID { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<int> CountDayes { get; set; }
        public Nullable<int> PlanVolume { get; set; }
        public Nullable<int> Price { get; set; }
        public Nullable<int> Group_Id { get; set; }
        public string Group_Name { get; set; }
        public Nullable<short> Speed_limit { get; set; }
        public Nullable<short> device_limit { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbLinks> tbLinks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbLinkUserAndPlans> tbLinkUserAndPlans { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbOrders> tbOrders { get; set; }
        public virtual tbServers tbServers { get; set; }
        public virtual tbUsers tbUsers { get; set; }
    }
}
