//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbRedisInfo
    {
        public int Redis_ID { get; set; }
        public string Redis_addr { get; set; }
        public int Redis_Port { get; set; }
        public string Redis_Password { get; set; }
    }
}
