//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbServers
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbServers()
        {
            this.tbLinks = new HashSet<tbLinks>();
            this.tbPlans = new HashSet<tbPlans>();
            this.tbUpdateLogs = new HashSet<tbUpdateLogs>();
            this.tbUseages = new HashSet<tbUseages>();
            this.tbUsers = new HashSet<tbUsers>();
        }
    
        public int ServerID { get; set; }
        public string ServerAddress { get; set; }
        public string ServerIP { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string DataBaseName { get; set; }
        public Nullable<bool> Status { get; set; }
        public string SubAddress { get; set; }
        public Nullable<long> BotID { get; set; }
        public string Robot_ID { get; set; }
        public string Robot_Token { get; set; }
        public string NowPayment_API_KEY { get; set; }
        public Nullable<double> Discount_Percent { get; set; }
        public Nullable<long> AdminTelegramUniqID { get; set; }
        public string Channel_ID { get; set; }
        public Nullable<double> FreeCredit { get; set; }
        public Nullable<int> PricePerGig { get; set; }
        public Nullable<int> PricePerMonth { get; set; }
        public Nullable<int> DefaultPlanIdInV2board { get; set; }
        public string BotbaseAddress { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbLinks> tbLinks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbPlans> tbPlans { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbUpdateLogs> tbUpdateLogs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbUseages> tbUseages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbUsers> tbUsers { get; set; }
    }
}
