//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbServers
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbServers()
        {
            this.tbPlans = new HashSet<tbPlans>();
            this.tbUpdateLogs = new HashSet<tbUpdateLogs>();
            this.tbUsers = new HashSet<tbUsers>();
        }
    
        public int ServerID { get; set; }
        public string ServerAddress { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string AdminPath { get; set; }
        public string Auth_Token { get; set; }
        public Nullable<bool> Status { get; set; }
        public string SubAddress { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbPlans> tbPlans { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbUpdateLogs> tbUpdateLogs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbUsers> tbUsers { get; set; }
    }
}
