//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbSocks5
    {
        public int tbsck_id { get; set; }
        public string tbsck_ip { get; set; }
        public Nullable<int> tbsck_port { get; set; }
        public string tbsck_username { get; set; }
        public string tbsck_password { get; set; }
        public bool IsActive { get; set; }
    }
}
