//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.DomainModel
{
    using System;
    using System.Collections.Generic;

    public partial class tbSupportLinks
    {
        public int tbSl_ID { get; set; }
        public int FK_User_ID { get; set; }
        public string tbSl_Title { get; set; }
        public string tbSl_Link { get; set; }
        public string tbSl_Phone { get; set; }

        public virtual tbUsers tbUsers { get; set; }
    }
}
