//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbTelegramUsers
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbTelegramUsers()
        {
            this.tbDepositWallet_Log = new HashSet<tbDepositWallet_Log>();
            this.tbLinks = new HashSet<tbLinks>();
            this.tbOrders = new HashSet<tbOrders>();
            this.tbTelegramUsers1 = new HashSet<tbTelegramUsers>();
        }
    
        public int Tel_UserID { get; set; }
        public string Tel_UniqUserID { get; set; }
        public string Tel_Step { get; set; }
        public string Tel_Username { get; set; }
        public string Tel_FirstName { get; set; }
        public string Tel_LastName { get; set; }
        public string Tel_RobotID { get; set; }
        public Nullable<int> Tel_Wallet { get; set; }
        public Nullable<int> Tel_Parent_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbDepositWallet_Log> tbDepositWallet_Log { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbLinks> tbLinks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbOrders> tbOrders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbTelegramUsers> tbTelegramUsers1 { get; set; }
        public virtual tbTelegramUsers tbTelegramUsers2 { get; set; }
    }
}
