//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbUpdateLogs
    {
        public int upl_ID { get; set; }
        public string upl_HostName { get; set; }
        public string upl_IPv4 { get; set; }
        public string upl_IPv6 { get; set; }
        public string upl_UserAgent { get; set; }
        public Nullable<System.DateTime> upl_CreateTime { get; set; }
        public string upl_AccountToken { get; set; }
        public Nullable<int> upl_FK_Server_ID { get; set; }
    
        public virtual tbServers tbServers { get; set; }
    }
}
