//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbUsers
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbUsers()
        {
            this.tbLinkUserAndPlans = new HashSet<tbLinkUserAndPlans>();
        }
    
        public int User_ID { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<int> FK_Server_ID { get; set; }
        public string Token { get; set; }
        public Nullable<int> Limit { get; set; }
        public Nullable<int> Wallet { get; set; }
        public Nullable<int> Role { get; set; }
        public string TelegramID { get; set; }
        public string BussinesTitle { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbLinkUserAndPlans> tbLinkUserAndPlans { get; set; }
        public virtual tbServers tbServers { get; set; }
    }
}
