//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbUsers
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbUsers()
        {
            this.tbBankCardNumbers = new HashSet<tbBankCardNumbers>();
            this.tbBotSettings = new HashSet<tbBotSettings>();
            this.tbConnectionHelp = new HashSet<tbConnectionHelp>();
            this.tbExpLog = new HashSet<tbExpLog>();
            this.tbFirebaseMobileTokens = new HashSet<tbFirebaseMobileTokens>();
            this.tbLinkServerGroupWithUsers = new HashSet<tbLinkServerGroupWithUsers>();
            this.tbLinkUserAndPlans = new HashSet<tbLinkUserAndPlans>();
            this.tbNotificationUser = new HashSet<tbNotificationUser>();
            this.tbPlans = new HashSet<tbPlans>();
            this.tbTelegramUsers = new HashSet<tbTelegramUsers>();
            this.tbUserFactors = new HashSet<tbUserFactors>();
            this.tbUsers1 = new HashSet<tbUsers>();
            this.tbHistoryChats = new HashSet<tbHistoryChats>();
            this.tbHistoryChats1 = new HashSet<tbHistoryChats>();
        }
    
        public int User_ID { get; set; }
        public string Username { get; set; }
        public Nullable<int> Parent_ID { get; set; }
        public string Password { get; set; }
        public string FullName { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string PhoneNumber { get; set; }
        public Nullable<bool> Status { get; set; }
        public string Email { get; set; }
        public Nullable<int> FK_Server_ID { get; set; }
        public string Token { get; set; }
        public Nullable<int> Limit { get; set; }
        public int Wallet { get; set; }
        public Nullable<int> Role { get; set; }
        public string TelegramID { get; set; }
        public string BussinesTitle { get; set; }
        public Nullable<long> Card_Number { get; set; }
        public Nullable<bool> IsRenew { get; set; }
        public Nullable<System.DateTime> ExpireTimeToken { get; set; }
        public Nullable<int> Admin_Telegram_ID { get; set; }
        public string Profile_Filename { get; set; }
        public bool GeneralAgent { get; set; }
        public Nullable<System.DateTime> Register_Date { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbBankCardNumbers> tbBankCardNumbers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbBotSettings> tbBotSettings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbConnectionHelp> tbConnectionHelp { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbExpLog> tbExpLog { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbFirebaseMobileTokens> tbFirebaseMobileTokens { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbLinkServerGroupWithUsers> tbLinkServerGroupWithUsers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbLinkUserAndPlans> tbLinkUserAndPlans { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbNotificationUser> tbNotificationUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbPlans> tbPlans { get; set; }
        public virtual tbServers tbServers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbTelegramUsers> tbTelegramUsers { get; set; }
        public virtual tbTelegramUsers tbTelegramUsers1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbUserFactors> tbUserFactors { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbUsers> tbUsers1 { get; set; }
        public virtual tbUsers tbUsers2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbHistoryChats> tbHistoryChats { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbHistoryChats> tbHistoryChats1 { get; set; }
    }
}
