//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbUserSetting
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbUserSetting()
        {
            this.tbUsers = new HashSet<tbUsers>();
        }
    
        public int UserSetting_ID { get; set; }
        public Nullable<int> Us_LimitTraffic { get; set; }
        public Nullable<int> Us_LimitMonth { get; set; }
        public bool Us_Status { get; set; }
        public Nullable<int> Us_CostTraffic { get; set; }
        public Nullable<int> Us_CostMonth { get; set; }
        public Nullable<int> Us_PlanDefaultInV2board { get; set; }
        public Nullable<short> Us_State { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbUsers> tbUsers { get; set; }
    }
}
