//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbUseages
    {
        public int tbUse_ID { get; set; }
        public Nullable<double> Download { get; set; }
        public Nullable<double> Upload { get; set; }
        public string Server_Record { get; set; }
        public Nullable<int> FK_Server_ID { get; set; }
        public Nullable<int> v2_User_ID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    
        public virtual tbServers tbServers { get; set; }
    }
}
