//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbUserFactors
    {
        public int tbUf_ID { get; set; }
        public Nullable<int> tbUf_Value { get; set; }
        public Nullable<System.DateTime> tbUf_CreateTime { get; set; }
        public Nullable<int> FK_User_ID { get; set; }
        public Nullable<int> tbUf_Status { get; set; }
        public string tbUf_FileName { get; set; }
        public string tbUf_Description { get; set; }
    
        public virtual tbUsers tbUsers { get; set; }
    }
}
