//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vi_AllSales
    {
        public string date { get; set; }
        public string year { get; set; }
        public string month { get; set; }
        public string day { get; set; }
        public Nullable<int> Order_Price { get; set; }
        public Nullable<int> FK_Tel_UserID { get; set; }
        public Nullable<int> User_Plan_ID { get; set; }
        public string Source { get; set; }
        public string BotId { get; set; }
    }
}
