//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vi_FullSales
    {
        public Nullable<int> PerYear { get; set; }
        public Nullable<int> User_ID { get; set; }
        public Nullable<int> PerMonth { get; set; }
        public Nullable<int> PerDay { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public int SaleRobot { get; set; }
        public int SalePanel { get; set; }
    }
}
