//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vi_MajorSales
    {
        public Nullable<long> Id { get; set; }
        public int log_ID { get; set; }
        public string Username { get; set; }
        public Nullable<int> SalePrice { get; set; }
        public Nullable<System.DateTime> CreateDatetime { get; set; }
    }
}
