//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vi_SaleFromBot
    {
        public int User_ID { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public Nullable<int> PerYear { get; set; }
        public Nullable<int> PerMonth { get; set; }
        public Nullable<int> PeyDay { get; set; }
        public Nullable<int> Sales { get; set; }
    }
}
